### ISSUE TITLE
Can't run same session file on one server

### ISSUE THREAD

**Issue by lucasnguyen3979** [Freddywhest/MajorBot#1]
Please fix this issue:
![image](https://github.com/user-attachments/assets/6eb1949c-f3ac-40ac-a0a4-5dd5a7325edd)

I use many versions of your bots on the same server, some will be kicked out or cannot load the session as shown in the picture.

**Comment by lucasnguyen3979** [comment]
Other error:
![image](https://github.com/user-attachments/assets/26bb55a1-f55f-45e3-bb8a-279e6303ed9a)

**Comment by Freddywhest** [comment]
Just create a new session.
References: 
https://github.com/telegramdesktop/tdesktop/issues/25144
https://github.com/tdlib/td/issues/353
https://github.com/LonamiWebs/Telethon/blob/v1.27.0/telethon_generator/data/errors.csv#L18

**Comment by lucasnguyen3979** [comment]
> Just create a new session. References: [telegramdesktop/tdesktop#25144](https://github.com/telegramdesktop/tdesktop/issues/25144) [tdlib/td#353](https://github.com/tdlib/td/issues/353) https://github.com/LonamiWebs/Telethon/blob/v1.27.0/telethon_generator/data/errors.csv#L18

So does that mean each bot will have to create a separate session for 1 account?

**Comment by Freddywhest** [comment]
Have you read all the references I provided?
